### ISSUE TITLE
API Response Nil

### ISSUE THREAD

**Issue by nidhisarvaiya** [elucid/ruby-freshbooks#5]
Hello,

We have been using this gem to fetch data from Freshbooks API form long time using API token authentication. It used to work pretty well for us.

Today, we are facing issue as response is being sent as Nil when we try to get list of invoices.

When we try to run below command for our client then we are getting below error

```
client.invoice.list

NoMethodError: undefined method `delete' for nil:NilClass
    from /home/ubuntu/.rvm/gems/ruby-2.0.0-p0/gems/ruby-freshbooks-0.4.1/lib/freshbooks.rb:17:in `initialize'
    from /home/ubuntu/.rvm/gems/ruby-2.0.0-p0/gems/ruby-freshbooks-0.4.1/lib/freshbooks.rb:66:in `new'
    from /home/ubuntu/.rvm/gems/ruby-2.0.0-p0/gems/ruby-freshbooks-0.4.1/lib/freshbooks.rb:66:in `post'
    from /home/ubuntu/.rvm/gems/ruby-2.0.0-p0/gems/ruby-freshbooks-0.4.1/lib/freshbooks.rb:121:in `method_missing'
    from (irb):3
    from /home/ubuntu/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.16/lib/rails/commands/console.rb:47:in `start'
    from /home/ubuntu/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.16/lib/rails/commands/console.rb:8:in `start'
    from /home/ubuntu/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.16/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

Any help will be greatly appreciated.

Thanks,
Nidhi Sarvaiya

**Comment by nidhisarvaiya** [comment]
Resolved the issue.
I was passing wrong API URL.
